[package]
name = "rust_main_project"
version = "0.1.0"
authors = ["Rodion Kovalenko <rodion.kovalenko@npo-applications.de>"]
edition = "2018"
build = "build.rs"

[lib]
name = "neural_networks"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.8.5"
serde = { version = "1.0.216", features = ["derive"] }
serde_derive = "1.0.216"
serde_json = "1.0.133"
num = "0.4"
num-complex = { version = "0.4", features = ["serde"] }
enigo = "0.3.0"
webbrowser = "1.0.3"
url = "2.2.1"
curl = "*"
futures = "0.3.30"
hyper = "1.5.1"
tokio = { version = "1.42.0", features = ["full"] }
reqwest = "0.12.9"
error-chain = "*"
chrono = {version="0.4.39",features = ["serde"]}
num-traits = "0.2.14"
cast = "0.3.0"
image = "0.25.5"
serde-big-array = "0.5.1"
sled = "0.34" 
tokenizers = "0.21.0"


[profile.release]
opt-level = "z" # Optimize for size
lto = true     # Enable Link Time Optimization
codegen-units = 1 # Reduce the number of codegen units to improve optimization
