#[cfg(feature = "dtype-f64")]
pub mod test_ffn_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_linear_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_rms_norm_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_softmax_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_self_attention_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_transformer;
#[cfg(feature = "dtype-f64")]
pub mod test_norm_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_serialization;
#[cfg(feature = "dtype-f64")]
pub mod test_sliding_window;
#[cfg(feature = "dtype-f64")]
pub mod test_self_attention_layer_with_loss;
#[cfg(feature = "dtype-f64")]
pub mod test_wavelet_complex_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_positional_encoding_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_attention_head_approximation;
#[cfg(feature = "dtype-f64")]
pub mod test_linear_matrix_mul;
#[cfg(feature = "dtype-f64")]
pub mod test_wavelet_compression;
#[cfg(feature = "dtype-f64")]
pub mod test_wavelet_discrete_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_adaptive_pooling_complex;
#[cfg(feature = "dtype-f64")]
pub mod test_self_attention_layer_appro_with_loss;
#[cfg(feature = "dtype-f64")]
pub mod test_sparse_self_attention_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_ffn_swiglu;
#[cfg(feature = "dtype-f64")]
pub mod test_sparse_self_attention_head;
#[cfg(feature = "dtype-f64")]
pub mod test_complex_to_linear_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_sparse_linear_layer;
#[cfg(feature = "dtype-f64")]
pub mod test_layer_input_ragged;